Feature/LEAF 1828/vue header (new)
department-of-veterans-affairs/LEAF pull request #1473
Opened 2021-09-21 21:13 UTC by aerinkayne

Header based on Jira ticket 1828.  Still in progress, but general feedback welcome.
(imo I don't think having the nav links on the left side, per the ticket, is better.  The menus are in the way, and people are used to them being elsewhere)

2021-09-22 12:50 UTC, AmandaSumner approved these changes

2021-09-24 12:35 UTC, Pelentan approved these changes
Looks good.

2021-09-24 18:01 UTC, raphaelfretter approved these changes

2021-09-24 18:31 UTC, gsteinhoff requested changes
The only issue I have with this is leaving in the commented-out code.  These should be removed as they can be retrieved in Github as needed for any reason.  Rest of it looks really good.

2021-09-24 18:31 UTC, gsteinhoff commented on LEAF_Request_Portal/admin/index.php
> +//nav (menu) is handled with vue component.  login does not look like it is still used
Are we removing these commented out code?  We shouldn't leave it in if no longer used.

2021-09-24 18:31 UTC, gsteinhoff commented on LEAF_Request_Portal/admin/templates/main.tpl
> +        {*
Again, we should remove old code if no longer using it.

2021-09-24 18:31 UTC, gsteinhoff commented on LEAF_Request_Portal/admin/templates/vue_components/leaf_header/vue_leaf_header.js
> +//site info  ISSUE not currently used
again commented code should be removed.

2021-09-29 13:48 UTC, gerald-todd approved these changes
Looks good

2021-09-29 20:56 UTC, gsteinhoff approved these changes
thanks for taking that commented code out

2022-01-12 14:32 UTC, closed without merging