bug: LEAF-2506 fix required currency bug
department-of-veterans-affairs/LEAF pull request #1476
Opened 2021-09-23 15:15 UTC by aerinkayne

Moved an empty string check prior to regex and Math methods.  
Please see test suggestions in the associated Jira ticket.

2021-09-23 15:48 UTC, AmandaSumner approved these changes

2021-09-23 15:51 UTC, maxrichardjr approved these changes
Looks good.

2021-09-23 16:21 UTC, gerald-todd approved these changes

2021-09-23 17:07 UTC, gsteinhoff approved these changes

2021-09-24 12:41 UTC, Pelentan requested changes

2021-09-24 12:41 UTC, Pelentan commented on LEAF_Request_Portal/templates/subindicators.tpl
> +                    if (value === ''){
Please get rid of all the "returns".  LINT screams at that.  The accepted method is to declare a return variable at the top of the function (ex $isNumeric = false;) and then fill/modify it as the code goes.  This keeps it to a single return and also helps maintain the return _type_.  Very important when we start tightening up our function calls.  ;-)

2021-09-24 15:01 UTC, raphaelfretter approved these changes

2021-09-24 18:15 UTC, Pelentan approved these changes
Much better.  Thank you.

2021-09-27 12:13 UTC, merged