LEAF 2599 tabbing and enter for employee selection
department-of-veterans-affairs/LEAF pull request #1516
Opened 2021-11-24 16:03 UTC by aerinkayne

Addresses the current inability of users to select orgchart employees from the table dropdowns by tab and enter.
Currently only applies to orgchart employee selection in forms (does not yet apply to report builder)

2021-11-24 16:16 UTC, AmandaSumner approved these changes
Looks Good

2021-11-24 16:40 UTC, maxrichardjr approved these changes
Looks good - no issues found in Test Automation

2021-11-24 18:41 UTC, gerald-todd approved these changes

2021-11-26 20:31 UTC, raphaelfretter approved these changes

2021-12-20 14:51 UTC, gsteinhoff approved these changes

2021-12-20 14:55 UTC, gerald-todd approved these changes

2022-01-03 14:42 UTC, Pelentan requested changes

2022-01-03 14:42 UTC, Pelentan commented on LEAF_Nexus/js/employeeSelector.js
> +	if(typeof event.key !== 'undefined' && event.key !== 'Enter') return;
Lets get into the mindset of always "cleaning" data before doing comparisons.  In this case, make event.key all lower case and compare to "enter".

2022-01-03 14:42 UTC, Pelentan commented on LEAF_Nexus/js/nationalEmployeeSelector.js
> +	if(typeof event.key !== 'undefined' && event.key !== "Enter") return; //for keypress events
And here

2022-01-04 16:15 UTC, Pelentan approved these changes

2022-01-06 17:40 UTC, merged