LEAF-2915: KILL CONNECTION_ID() line is causing warnings
department-of-veterans-affairs/LEAF pull request #1587
Opened 2022-06-16 14:04 UTC by raphaelfretter

2022-06-16 14:10 UTC, Pelentan requested changes

2022-06-16 14:10 UTC, Pelentan commented on LEAF_Request_Portal/db_mysql.php
> +            $this->db->query('KILL CONNECTION_ID()');
Need logging for both succeed and fail on the try/catch.  Would like to see if this is working at all.  When we added it last year, it did seem to clear up some things, but that could have been do to other things.

2022-06-16 15:15 UTC, Pelentan approved these changes

2022-06-16 16:06 UTC, pete-nerantzinis approved these changes

2022-06-22 11:19 UTC, aerinkayne approved these changes

2022-06-23 13:47 UTC, gerald-todd approved these changes

2022-06-27 18:20 UTC, merged