LEAF 2833 'Choicesjs' plugin for multiselect questions
department-of-veterans-affairs/LEAF pull request #1614
Opened 2022-07-25 18:44 UTC by aerinkayne

Please see Jira ticket 2833 for details.

2022-07-25 18:48 UTC, AmandaSumner approved these changes

2022-07-25 19:53 UTC, maxrichardjr approved these changes
Great!

2022-07-26 13:58 UTC, raphaelfretter approved these changes

2022-07-26 15:45 UTC, pete-nerantzinis approved these changes

2022-07-26 21:13 UTC, Pelentan requested changes

2022-07-26 21:13 UTC, Pelentan commented on LEAF_Request_Portal/templates/subindicators.tpl
> +                            function decodeHTMLEntities(str) {
Why is this function buried in multiple levels?  This looks like it should be on the root level.

2022-08-18 14:45 UTC, Pelentan approved these changes

2022-08-23 13:51 UTC, merged