LEAF-2911: Syncservices Employee Synchronization Fix
department-of-veterans-affairs/LEAF pull request #1658
Opened 2022-09-09 18:24 UTC by pete-nerantzinis

2022-09-09 19:00 UTC, raphaelfretter approved these changes

2022-09-09 19:12 UTC, shaneodd approved these changes

2022-09-13 17:24 UTC, aerinkayne approved these changes

2022-09-14 00:18 UTC, Pelentan requested changes

2022-09-14 15:18 UTC, Pelentan approved these changes

2022-09-14 15:34 UTC, AmandaSumner approved these changes

2022-09-14 16:13 UTC, maxrichardjr approved these changes

2022-09-15 13:27 UTC, pete-nerantzinis commented on LEAF_Request_Portal/admin/Group.php
> +                $res = $this->db->prepared_query('SELECT * FROM users WHERE userID=:userID AND groupID=:groupID AND backupID=:backupID', $sql_vars);
Changed to locallyManaged

2022-09-15 13:27 UTC, pete-nerantzinis commented on LEAF_Request_Portal/admin/templates/mod_groups.tpl
> +        data: {'CSRFToken': '<!--{$CSRFToken}-->'},
Added

2022-09-20 13:59 UTC, merged