LEAF 3072 Form Editor refresh
department-of-veterans-affairs/LEAF pull request #1680
Opened 2022-09-30 18:52 UTC by aerinkayne

general review/ comments only

2022-10-04 13:37 UTC, shaneodd approved these changes

2022-10-04 13:44 UTC, maxrichardjr approved these changes

2022-10-04 17:26 UTC, raphaelfretter commented on libs/js/LEAF/form_editor_vue_src/components/dialog_content/AdvancedOptionsDialog.js
> +        console.log('Advanced Options mounted', this.currIndicatorID, this.formID);
Probably want to get rid of these console logs after some time.

2022-10-14 13:08 UTC, Pelentan requested changes

2022-10-25 13:30 UTC, aerinkayne commented
closing general review

2022-10-25 13:30 UTC, closed without merging