LEAF 3139.  508 issues
department-of-veterans-affairs/LEAF pull request #1683
Opened 2022-10-06 13:03 UTC by aerinkayne

Addresses a variety of 508/screen reader issues associated with page navigation and form entry/submission.

2022-10-06 13:17 UTC, maxrichardjr approved these changes

2022-10-06 14:03 UTC, Pelentan approved these changes

2022-10-06 14:09 UTC, AmandaSumner approved these changes

2022-10-06 14:10 UTC, pete-nerantzinis approved these changes

2022-10-06 14:15 UTC, shaneodd approved these changes

2022-10-06 15:22 UTC, raphaelfretter requested changes

2022-10-06 15:22 UTC, raphaelfretter commented on LEAF_Nexus/templates/view_homepage.tpl
> +                $('#data_28_1_1').css('word-break', 'break-word');
Either word-break: normal or overflow-wrap: anywhere would be better. break-word is deprecated.

2022-10-12 13:07 UTC, raphaelfretter approved these changes

2022-10-13 11:53 UTC, merged