LEAF  3150 UI update for IFTHEN multiselect scenarios
department-of-veterans-affairs/LEAF pull request #1688
Opened 2022-10-13 11:34 UTC by aerinkayne

Multiselect format questions were recently fully enabled for the condition editor (IFTHEN).
This update adds the choicesjs multiselect combobox to the conditions editor.  
It will now appear in place of a standard select box when
-a multiselect question is the parent, 
-a multiselect child has a pre-fill value

Also, the overall template for this app had changed considerably since its initial development, with the vast majority now associated with one component and the others consisting only of a few lines.  These have been combined to simplify the overall app (no prop drilling) and facilitate future developments in the form editor area.

2022-10-13 12:05 UTC, Pelentan requested changes

2022-10-13 12:05 UTC, Pelentan commented on LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
> +        removeCondition(data) {
type hinting please.

2022-10-13 12:05 UTC, Pelentan commented on LEAF_Request_Portal/js/vue_conditions_editor/LEAF_conditions_editor.js
> +            if(parentFormat === 'multiselect' && elSelectParent !== null && !elSelectParent.choicesjs) {
Just a note for future consideration:  We're going to want to have a map for these selections so we can compare ints instead of strings.

2022-10-13 12:22 UTC, jampaul3 approved these changes

2022-10-13 13:09 UTC, maxrichardjr approved these changes

2022-10-13 16:01 UTC, shaneodd approved these changes
From what I see comments, I do not think that would hold something back, type hinting would.

2022-10-14 01:15 UTC, maxrichardjr approved these changes

2022-10-14 15:20 UTC, Pelentan approved these changes

2022-10-14 17:17 UTC, AmandaSumner approved these changes

2022-10-17 18:27 UTC, merged