LEAF  3165 - 508 improvements follow-up (new)
department-of-veterans-affairs/LEAF pull request #1691
Opened 2022-10-17 15:08 UTC by aerinkayne

Adds specific aria labels for various question formats (grids, org groups, positions, single and multiselect dropdowns, checkbox/es and radio inputs).  Adds additional html landmark elements and tabbing to initial form page and associated style updates.  Adds keyboard input controls for form navtree menu.

2022-10-17 15:16 UTC, jampaul3 approved these changes

2022-10-17 17:04 UTC, maxrichardjr approved these changes

2022-10-17 20:49 UTC, shaneodd requested changes
in the for loops vars should be lets, could lead to odd behavior otherwise.

2022-10-17 20:49 UTC, shaneodd commented on LEAF_Request_Portal/js/gridInput.js
>          for(var i = 0; i < options.length; i++){
I believe these vars should be lets.

2022-10-20 15:06 UTC, shaneodd approved these changes

2022-10-24 15:15 UTC, AmandaSumner approved these changes

2022-10-26 12:31 UTC, raphaelfretter approved these changes

2022-10-27 14:08 UTC, merged