LEAF 3188 fileupload and image format template updates
department-of-veterans-affairs/LEAF pull request #1702
Opened 2022-10-27 14:45 UTC by aerinkayne

Replaces the iframes used for file attachments in the subindicators template with standard input type=file elements.  Associated prior code in other templates is being retained for use in custom subindicators files, which will continue to use these older templates.

Also adjusts some styling to meet contrast recommendations, fixes a button display issue and updates some error message verbiage.

Any code associated with file deletions will be handled in a future ticket to resolve uncovered issues that are unrelated to this update.

2022-10-27 15:08 UTC, maxrichardjr approved these changes

2022-10-27 17:12 UTC, shaneodd approved these changes

2022-10-28 11:17 UTC, jampaul3 approved these changes

2022-11-02 11:39 UTC, pete-nerantzinis approved these changes

2022-11-03 20:05 UTC, raphaelfretter approved these changes

2022-11-08 17:36 UTC, Pelentan requested changes

2022-11-08 17:36 UTC, Pelentan commented on LEAF_Request_Portal/templates/subindicators.tpl
> +                                        success: function(response) {
fail check?

2022-11-09 13:52 UTC, maxrichardjr approved these changes

2023-03-10 14:23 UTC, closed without merging