LEAF-3199 clearer next step
department-of-veterans-affairs/LEAF pull request #1705
Opened 2022-10-31 13:45 UTC by jampaul3

Previously, for a non-admin if you were to go to the request page to view a request and the dependencyID was a -1 or -3 the title on the page would say Pending action from null. Now, when you go to this page you will see the stepTitle which matches the home page status column.

2022-10-31 18:05 UTC, shaneodd approved these changes

2022-11-01 19:22 UTC, raphaelfretter approved these changes

2022-11-02 11:38 UTC, pete-nerantzinis approved these changes

2022-11-08 00:11 UTC, aerinkayne reviewed
Is it certain this is a bug and not possibly a local issue?  On master I get 'pending action from <employee name>', and now on this branch I get 'pending action from Submit', which has its own issues.  It might be that we just need to handle a situation where the property that usually has the name is unexpectedly null.  I know in the inbox area we add 'unknown user' instead.

2022-11-08 16:20 UTC, aerinkayne approved these changes

2022-11-08 17:33 UTC, Pelentan approved these changes

2022-11-09 20:39 UTC, AmandaSumner approved these changes

2022-11-15 19:40 UTC, pete-nerantzinis approved these changes

2022-11-15 19:49 UTC, shaneodd approved these changes

2022-11-15 19:56 UTC, Pelentan approved these changes

2022-11-15 19:57 UTC, raphaelfretter requested changes

2022-11-15 19:57 UTC, raphaelfretter commented on LEAF_Request_Portal/js/workflow.js
> +                    let name = 'Pending action from ' + res[currRecordID]['s1']['id' + step.indicatorID_for_assigned_empUID] || "Warning: User not selected for currennt action (Contact Administrator)
```suggestion
                    let name = 'Pending action from ' + res[currRecordID]['s1']['id' + step.indicatorID_for_assigned_empUID] || "Warning: User not selected for current action (Contact Administrator)";
```

2022-11-15 20:24 UTC, raphaelfretter approved these changes

2022-11-15 21:02 UTC, merged