fix input type
department-of-veterans-affairs/LEAF pull request #1757
Opened 2022-11-18 21:35 UTC by mgaoVA

Fixes an issue with non-selfclosing textarea tag

2022-11-18 21:37 UTC, aerinkayne approved these changes

2022-11-18 21:38 UTC, pete-nerantzinis approved these changes

2022-11-18 23:55 UTC, maxrichardjr approved these changes

2022-11-21 14:06 UTC, raphaelfretter approved these changes

2022-11-21 14:27 UTC, jampaul3 approved these changes

2022-11-21 16:36 UTC, Pelentan approved these changes

2022-11-21 17:47 UTC, shaneodd requested changes
Would this also need to update the edit form as well? That would still have textareas as well.

2022-11-21 19:08 UTC, AmandaSumner approved these changes

2022-11-21 19:41 UTC, shaneodd approved these changes
Discussed with @mgaoVA if we should also update the edit side of this as well and did the update there as well.

2022-11-21 20:55 UTC, merged