Leaf-3198 step 1 arrange classes in class folders
department-of-veterans-affairs/LEAF pull request #1767
Opened 2022-12-01 15:56 UTC by jampaul3

Step 1 was to get all the class files into class folders, rather than have them placed willy nilly. All classes are now in sources and in the api folders. I didn't really change the api and controller folders. In moving the files I had to make sure they were being included correctly as well. So all files that uses a moved class file has changed as well.

2022-12-01 16:25 UTC, maxrichardjr approved these changes
I realize it was largely changes to path for mySQL and config.php, but it was a ton of changes, 83 files!!

2022-12-05 18:13 UTC, raphaelfretter requested changes

2022-12-05 18:13 UTC, raphaelfretter commented on LEAF_Request_Portal/templates/print_form.tpl
> +                console.log('it was a success with NO errors');
Should not need logs here for production.

2022-12-05 18:13 UTC, raphaelfretter commented on LEAF_Request_Portal/templates/print_form.tpl
> +                console.log('it was a succes with errors');
Here too.

2022-12-05 21:52 UTC, shaneodd approved these changes

2022-12-08 13:18 UTC, jampaul3 commented on LEAF_Request_Portal/templates/print_form.tpl
> +                console.log('it was a succes with errors');
removed

2022-12-12 16:30 UTC, raphaelfretter approved these changes

2022-12-12 22:19 UTC, aerinkayne approved these changes

2022-12-23 16:06 UTC, closed without merging