LEAF-3434: Combined Inbox Part 1: Update sitemap editor
department-of-veterans-affairs/LEAF pull request #1839
Opened 2023-02-10 18:51 UTC by raphaelfretter

https://vajira.max.gov/browse/LEAF-3434

2023-02-10 19:51 UTC, maxrichardjr approved these changes

2023-02-10 19:52 UTC, maxrichardjr approved these changes

2023-02-10 20:34 UTC, shaneodd requested changes

2023-02-10 20:34 UTC, shaneodd commented on LEAF_Request_Portal/sources/IconPIcker.php
> +class IconPicker
Coding standards for classes should apply here, return types and typed variables.

2023-02-10 20:34 UTC, shaneodd commented on LEAF_Request_Portal/api/controllers/IconPickerController.php
> +class IconPickerController extends RESTfulResponse
Some of the coding standards for classes could apply here, not sure how return types would operate here at a glance. Maybe bring this up for discussion.

2023-02-13 16:19 UTC, maxrichardjr approved these changes

2023-02-13 17:43 UTC, maxrichardjr approved these changes

2023-02-13 17:56 UTC, maxrichardjr approved these changes

2023-02-13 17:56 UTC, maxrichardjr approved these changes

2023-02-13 18:45 UTC, shaneodd approved these changes

2023-02-13 19:46 UTC, Pelentan approved these changes

2023-02-13 20:07 UTC, aerinkayne reviewed
The target site address has a max limit of 40 chars, which probably isn't enough for some sites.  Otherwise looks good (description length could maybe be bumped a little too, but there's not much more space on the cards anyway)

2023-02-13 21:07 UTC, AmandaSumner approved these changes

2023-02-14 00:15 UTC, maxrichardjr approved these changes

2023-02-14 00:15 UTC, maxrichardjr approved these changes

2023-02-14 12:34 UTC, aerinkayne approved these changes

2023-02-22 15:06 UTC, merged