LEAF 3327 New Account Updater
department-of-veterans-affairs/LEAF pull request #1840
Opened 2023-02-13 19:45 UTC by aerinkayne

Adds functionality to the 'Initiator New Account' report (previous name on Menu / Toolbox card).

In addition to updating request initiator, this report should now search for orgchart_employee fields, user groups, and employee position assignments and allow admins to mass update these fields.

2023-02-13 21:36 UTC, maxrichardjr approved these changes

2023-02-14 13:12 UTC, raphaelfretter requested changes

2023-02-14 22:15 UTC, maxrichardjr approved these changes

2023-02-15 18:01 UTC, shaneodd approved these changes

2023-02-15 18:03 UTC, raphaelfretter requested changes

2023-02-15 18:03 UTC, raphaelfretter commented on LEAF_Nexus/sources/Employee.php
> +    public function lookupLogin($login, bool $searchDeleted = false): array
My bad, comment block here too.

2023-02-15 19:08 UTC, Pelentan requested changes

2023-02-15 19:08 UTC, Pelentan commented on LEAF_Request_Portal/admin/templates/mod_account_updater.tpl
> +    switch(item.taskType) {
toLower()

2023-02-15 19:37 UTC, maxrichardjr approved these changes

2023-02-15 22:28 UTC, maxrichardjr approved these changes

2023-02-16 13:43 UTC, Pelentan approved these changes

2023-02-16 15:19 UTC, jrodcode approved these changes

2023-02-17 14:10 UTC, raphaelfretter approved these changes

2023-02-17 18:37 UTC, maxrichardjr approved these changes

2023-02-21 13:50 UTC, maxrichardjr approved these changes

2023-02-22 18:41 UTC, AmandaSumner approved these changes

2023-02-24 23:59 UTC, maxrichardjr approved these changes

2023-02-28 13:18 UTC, merged