Enhance/LEAF-2390/improve-group-form-history
department-of-veterans-affairs/LEAF pull request #1861
Opened 2023-03-01 15:05 UTC by raphaelfretter

vars/methods that aren't being used: 
FormatOptions::DISPLAY
dataActionLogger::findExternalValue()
any const TABLE in the formatter files
"key" and "display" columns in modify-indicator template

2023-03-02 14:32 UTC, shaneodd approved these changes

2023-03-10 12:53 UTC, pete-nerantzinis requested changes
Need to merge in master and fix conflicts as the files have been renamed to capitals and not the lowercases, also there are some require_once's and instantiations that are not needed anymore since autoloader loads them for us now.

2023-03-10 19:35 UTC, jampaul3 commented on libs/logger/DataActionLogger.php
for classes the { is supposed to be on the next line by itself. According to PSR12 and for the rest of the files.

2023-03-10 19:36 UTC, jampaul3 commented on libs/logger/formatters/EmailTemplateFormatter.php
> +}
PSR12 also wants a blank line at the end of a php only file.

2023-03-10 19:37 UTC, jampaul3 approved these changes

2023-03-10 21:09 UTC, pete-nerantzinis approved these changes

2023-03-10 21:27 UTC, aerinkayne approved these changes

2023-03-15 13:10 UTC, shaneodd approved these changes

2023-03-21 14:01 UTC, merged