LEAF-3568 - Copy request_service does not show on non admin
department-of-veterans-affairs/LEAF pull request #1878
Opened 2023-03-10 20:33 UTC by shaneodd

When copying a request, services were not showing when a user was not an admin, this was due to the services call being an admin only call. I did not see any reason for this since none of the other sections working with services in this way needed to be admin only.

2023-03-10 21:04 UTC, maxrichardjr approved these changes

2023-03-12 03:24 UTC, mgaoVA requested changes
All functions referenced in the POST and DELETE sections will need an admin check.

2023-03-16 19:08 UTC, pete-nerantzinis approved these changes

2023-03-17 15:47 UTC, raphaelfretter approved these changes

2023-03-17 18:57 UTC, shaneodd commented
> All functions referenced in the POST and DELETE sections will need an admin check.

I added in logic for the post and delete to have those checks in place. My initial change would have affected this.

2023-03-17 19:04 UTC, maxrichardjr approved these changes
Appears to be correct from my perspective

2023-03-17 19:25 UTC, aerinkayne approved these changes

2023-03-21 15:10 UTC, Pelentan requested changes

2023-03-22 15:48 UTC, Pelentan approved these changes

2023-03-22 15:51 UTC, shaneodd commented on LEAF_Request_Portal/api/controllers/ServiceController.php
> +        if ($login->checkGroup(1)) {
It returns true if the group is there, null if it is not there. This is used across the site and would probably be better served to update the checkGroup function so return false to fully fulfil how it should be. We had a quick discussion and determined this was a code grooming item for a later time.

2023-03-22 17:52 UTC, AmandaSumner approved these changes

2023-03-29 15:39 UTC, merged