Leaf 3176 - refactor RESTfulResponse
department-of-veterans-affairs/LEAF pull request #1896
Opened 2023-03-24 14:39 UTC by jampaul3

So the refactor of RESTfulResponse in complete. This refactor added type hinting and removed the echo's that were within the file.

Some of the echo's were moved to the individual controller classes, which isn't any better than what was there before, but I felt it was outside the scope of this ticket to go further than this. To fix those later will have to be another ticket. 

I believe the type hinting is all good. I was able to test locally with no php errors or console errors. But that is going to be the thing to watch for in testing.

2023-03-24 15:21 UTC, maxrichardjr approved these changes

2023-03-24 18:43 UTC, maxrichardjr approved these changes

2023-03-24 20:21 UTC, raphaelfretter reviewed
Is there a reason to echo the calls in the index files? Does it go to a log of some kind?

2023-03-27 13:49 UTC, jampaul3 commented
@raphaelfretter functionality should be exactly as it was. I didn't want to make any more changes than necessary. So the echo's were in the RESTfulResponse, but in order to clean the class up I moved them out the the index. Classes shouldn't have echo's in them if the are processing data which these classes are. The echo will be sent back as part of the response to the api call, as it did previously. It's just now being sent from the index rather than the class.

A good question here would be, is this the proper way to do it? That I can't answer right now, but the changes I made here was to clean up the RESTfulResponse while keeping the overall functionality the same.

2023-03-27 14:44 UTC, raphaelfretter commented
> @raphaelfretter functionality should be exactly as it was. I didn't want to make any more changes than necessary. So the echo's were in the RESTfulResponse, but in order to clean the class up I moved them out the the index. Classes shouldn't have echo's in them if the are processing data which these classes are. The echo will be sent back as part of the response to the api call, as it did previously. It's just now being sent from the index rather than the class.
> 
> A good question here would be, is this the proper way to do it? That I can't answer right now, but the changes I made here was to clean up the RESTfulResponse while keeping the overall functionality the same.

That makes sense. I don't know of an alternative off the top of my head.

2023-03-27 14:44 UTC, raphaelfretter approved these changes

2023-03-27 15:48 UTC, shaneodd approved these changes

2023-03-27 15:55 UTC, aerinkayne approved these changes

2023-03-28 18:33 UTC, Pelentan requested changes

2023-03-28 18:33 UTC, Pelentan commented on LEAF_Request_Portal/api/controllers/FormEditorController.php
> +            echo $verified;
Is this supposed to be commented out?

2023-03-28 18:33 UTC, Pelentan commented on LEAF_Request_Portal/api/controllers/FormStackController.php
> +            echo $verified;
And this?  Might want to do a search on "echo"s

2023-03-28 18:33 UTC, Pelentan commented on LEAF_Request_Portal/api/controllers/GroupController.php
> +            echo $verified;
echo

2023-03-28 18:33 UTC, Pelentan commented on LEAF_Request_Portal/api/index.php
> +    echo $controller->handler($action);
Are these echos supposed to be here?

2023-03-28 20:57 UTC, AmandaSumner approved these changes

2023-03-29 16:13 UTC, merged