Leaf 3611 adding signature to db
department-of-veterans-affairs/LEAF pull request #1928
Opened 2023-04-05 14:39 UTC by jampaul3

2023-04-05 14:57 UTC, maxrichardjr approved these changes

2023-04-06 12:40 UTC, shaneodd approved these changes

2023-04-06 16:59 UTC, raphaelfretter requested changes

2023-04-06 16:59 UTC, raphaelfretter commented on LEAF_Request_Portal/admin/templates/mod_form.tpl
> +                <option value="signature">Signature</option>
Be sure to comment out since this isn't the whole functionality.

2023-04-06 17:13 UTC, jrodcode approved these changes

2023-04-07 12:55 UTC, maxrichardjr approved these changes

2023-04-07 13:08 UTC, pete-nerantzinis approved these changes

2023-04-11 16:09 UTC, Pelentan requested changes

2023-04-11 16:09 UTC, Pelentan commented on LEAF_Request_Portal/sources/Signature.php
> +    public function create($signature, $recordID, $stepID, $dependencyID, $message, $signerPublicKey): int
Can we do type-hinting here?

2023-04-12 13:38 UTC, jampaul3 commented on LEAF_Request_Portal/sources/Signature.php
> +    public function create($signature, $recordID, $stepID, $dependencyID, $message, $signerPublicKey): int
Added.

2023-04-12 13:54 UTC, maxrichardjr approved these changes

2023-04-12 16:31 UTC, AmandaSumner approved these changes

2023-04-18 14:14 UTC, merged