LEAF 3451 Site Designer entry and menu card customization (review only)
department-of-veterans-affairs/LEAF pull request #1952
Opened 2023-04-25 13:28 UTC by aerinkayne

This branch is part of a longer term epic and is not currently planned for deployment.

Adds a 'Site Designer' admin menu card (Admin Home, Toolbox) to Site Designer admin area template.
This area can be used to add and customize home menu links as well as to enable/disable use of the customized homepage.

This branch also restructures the vue-app src folder to separate Form Editor, Site Designer and Common files, and updates the Vue container configs and scripts.   A rebuild will be needed to actively develop these apps.

2023-04-25 14:48 UTC, maxrichardjr approved these changes
Looks good to me Carrie

2023-04-26 12:53 UTC, maxrichardjr approved these changes

2023-04-27 13:17 UTC, raphaelfretter requested changes

2023-04-27 13:17 UTC, raphaelfretter commented on libs/js/vue-dest/135.chunk.js
Did we want to keep these chunk files? If not, need to add them to the gitignore

2023-04-27 18:18 UTC, Pelentan approved these changes

2023-04-27 20:07 UTC, aerinkayne commented on libs/js/vue-dest/135.chunk.js
They are chunk files for the main form editor build, since otherwise it is getting quite large.  It'd be better if they were in the FE folder but I haven't been able to get them to build there.  Either way they are part of the app.

2023-04-27 20:09 UTC, aerinkayne commented on LEAF_Request_Portal/admin/index.php
> +            $main->assign('body', 'You require System Administrator level access to view this section.');
This is the same block that is in other cases copy-pasted with the file name changed

2023-05-01 11:35 UTC, raphaelfretter approved these changes

2023-05-01 12:53 UTC, maxrichardjr approved these changes

2023-05-01 12:54 UTC, maxrichardjr approved these changes

2023-05-01 12:55 UTC, maxrichardjr approved these changes

2023-05-01 16:05 UTC, AmandaSumner approved these changes

2023-05-02 14:46 UTC, maxrichardjr approved these changes

2023-05-02 15:51 UTC, shaneodd approved these changes

2023-05-08 11:37 UTC, jampaul3 approved these changes

2023-05-16 19:35 UTC, closed without merging