LEAF-3696 Email Template Update
department-of-veterans-affairs/LEAF pull request #1977
Opened 2023-05-19 14:05 UTC by jrodcode

Previously, users encountered an issue with the email template saving feature. The system would only allow them to save a section if they made a change to the body of the email. However, the problem is now resolved. Users can save a section without needing to make any changes in the body of the email.

2023-05-19 15:25 UTC, maxrichardjr approved these changes

2023-05-22 14:19 UTC, Pelentan requested changes

2023-05-22 14:19 UTC, Pelentan commented on LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
> +                    success: function(res) {
not seeing a fail-catch.

2023-05-22 21:35 UTC, jrodcode commented on LEAF_Request_Portal/admin/templates/mod_templates_email.tpl
> +        const emailToData = document.getElementById('emailToCode').value;
I have made changes to the code, please review.

2023-05-23 12:47 UTC, maxrichardjr approved these changes

2023-05-23 13:30 UTC, jampaul3 approved these changes

2023-05-23 16:58 UTC, shaneodd approved these changes

2023-05-24 16:34 UTC, maxrichardjr approved these changes

2023-05-25 12:56 UTC, maxrichardjr approved these changes

2023-05-25 14:58 UTC, Pelentan approved these changes

2023-05-25 15:27 UTC, maxrichardjr approved these changes

2023-05-31 12:31 UTC, AmandaSumner approved these changes

2023-06-06 14:44 UTC, merged