LEAF-3436: Combined Inbox Customization
department-of-veterans-affairs/LEAF pull request #1981
Opened 2023-05-25 16:44 UTC by raphaelfretter

2023-05-25 20:22 UTC, pete-nerantzinis approved these changes

2023-05-30 12:02 UTC, jampaul3 approved these changes

2023-05-30 17:00 UTC, shaneodd approved these changes

2023-05-31 14:22 UTC, Pelentan requested changes

2023-05-31 14:22 UTC, Pelentan commented on LEAF_Request_Portal/admin/templates/view_admin_menu.tpl
> +        $.ajax({
fail catch

2023-05-31 15:13 UTC, aerinkayne approved these changes

2023-05-31 19:02 UTC, Pelentan approved these changes

2023-05-31 19:04 UTC, maxrichardjr approved these changes

2023-06-01 20:36 UTC, AmandaSumner approved these changes

2023-06-02 12:54 UTC, maxrichardjr approved these changes

2023-06-02 20:48 UTC, maxrichardjr approved these changes

2023-06-06 14:42 UTC, merged