Leaf 3546 - API code consistency
department-of-veterans-affairs/LEAF pull request #1984
Opened 2023-05-30 12:08 UTC by jampaul3

This just renames 2 API endpoints.

2023-05-30 13:56 UTC, maxrichardjr approved these changes

2023-05-31 16:27 UTC, raphaelfretter requested changes

2023-05-31 17:10 UTC, jampaul3 commented on LEAF_Request_Portal/templates_history/template_editor/1685036655_view_homepage.tpl
no, hence the reason we need the LEAF_Request_Portal/templates_history/* in the gitignore file. We don't want these to get pushed to anything. These were just created in my testing.

2023-05-31 17:51 UTC, pete-nerantzinis approved these changes
Approving but please test this since there are so many changes we might even need to do a search on the reportTemplates as there could be custom code with those api calls.

2023-05-31 18:00 UTC, jrodcode approved these changes

2023-06-01 15:34 UTC, Pelentan approved these changes

2023-06-01 17:28 UTC, AmandaSumner approved these changes

2023-06-02 12:48 UTC, aerinkayne approved these changes
Just noting other comments about gitignore for template hsitory tracking (and custom override templates too if it does not cause issues)

2023-06-05 13:23 UTC, mgaoVA commented
@jampaul3 For API renames:

1. The old API should remain active should remain until we can show that it hasn't been used in the past 30 days
2. While the old API is active, there should be a comment to indicate its deprecation status, and reference the new API

If we find that its being used after we stop using it ourselves, we'll need to reach out to the site admins still using it and request that they update their customizations.

2023-06-05 15:38 UTC, maxrichardjr approved these changes

2023-06-06 14:40 UTC, merged