LEAF-3713: Smart field in email template
department-of-veterans-affairs/LEAF pull request #2008
Opened 2023-06-20 16:42 UTC by raphaelfretter

2023-06-20 17:09 UTC, Pelentan requested changes

2023-06-20 17:09 UTC, Pelentan commented on LEAF_Request_Portal/sources/FormWorkflow.php
> +            switch(true) {
Ok.  Need to make these case insensitive.  Recommend strToLower() on $format above.

2023-06-20 17:09 UTC, Pelentan commented on LEAF_Request_Portal/sources/FormWorkflow.php
> +    private function buildGrid($data): string
type hinting.

2023-06-20 17:15 UTC, pete-nerantzinis approved these changes

2023-06-20 19:38 UTC, maxrichardjr approved these changes

2023-06-21 18:32 UTC, Pelentan approved these changes

2023-06-22 12:14 UTC, jampaul3 approved these changes

2023-06-22 19:36 UTC, shaneodd approved these changes

2023-06-22 19:36 UTC, shaneodd commented on LEAF_Request_Portal/sources/FormWorkflow.php
> +
I would suggest we make sure we have phpdocs here as well. Helps with adding context when needed and helps fill in the intellisense a bit more with what is actually going on.

2023-06-22 19:50 UTC, AmandaSumner approved these changes

2023-06-26 18:44 UTC, maxrichardjr approved these changes

2023-06-27 13:07 UTC, merged