LEAF-3836 - GitHub repo Not Mapped to eMASS ssystem
department-of-veterans-affairs/LEAF pull request #2030
Opened 2023-07-05 15:00 UTC by shaneodd

add in emass file that is required within the issue on the github repo, this is a file in the .github folder so no programming code was effected. From what Albert says the system on their end should just pick it up with no further action from us. Once the code is merged into master I think we can close the issue out.

2023-07-05 19:56 UTC, maxrichardjr approved these changes

2023-07-05 19:57 UTC, maxrichardjr approved these changes

2023-07-06 13:31 UTC, jampaul3 approved these changes

2023-07-07 12:32 UTC, jrodcode approved these changes

2023-07-07 13:09 UTC, raphaelfretter approved these changes

2023-07-10 12:57 UTC, Pelentan requested changes
This is a duplicate.  This is handled under the CodeQL branch

2023-07-10 13:24 UTC, closed without merging