LEAF-3822: Destruction of LEAF Records
department-of-veterans-affairs/LEAF pull request #2070
Opened 2023-08-01 19:44 UTC by pete-nerantzinis

2023-08-03 13:39 UTC, raphaelfretter commented on docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023072000-2023080100.sql
> +ALTER TABLE records_dependencies DROP FOREIGN KEY fk_records_dependencies_deletion;
Shouldn't the table be dropped after the foreign keys?

2023-08-03 16:13 UTC, shaneodd approved these changes

2023-09-11 17:13 UTC, Pelentan requested changes

2023-09-11 17:13 UTC, Pelentan commented on LEAF_Request_Portal/sources/FormEditor.php
> +    public function setFormDestructionAge(string $categoryID, int $input = null): int|null {
Since this is all brand new, we should be able to set the return up right.  Meaning the array/json version with the two parts.

2023-09-11 17:13 UTC, Pelentan commented on LEAF_Request_Portal/sources/FormEditor.php
> +        if ($categoryID) {
Pretty sure this isn't a boolean.

2023-09-11 17:13 UTC, Pelentan commented on LEAF_Request_Portal/sources/FormEditor.php
> +    public function getDestructionAge(string $categoryID): int|null
Same here

2023-09-11 17:13 UTC, Pelentan commented on docker/mysql/db/db_upgrade/portal/Update_RMC_DB_2023072000-2023080100.sql
> +ALTER TABLE records_dependencies ADD CONSTRAINT fk_records_dependencies_deletion
I'm betting this is going to be a sllloooowww roll out.

2023-10-03 12:14 UTC, merged