LEAF-3776: LDAP Research
department-of-veterans-affairs/LEAF pull request #2091
Opened 2023-08-17 16:16 UTC by raphaelfretter

The only functional change is the save button in import groups says 'import'. AD API endpoints are inaccessible but in place until AD server routing issue is resolved.

2023-08-18 18:00 UTC, Pelentan requested changes

2023-08-18 18:00 UTC, Pelentan commented on LEAF_Nexus/sources/ActiveDirectory.php
> +      if ($this->bind) {
This isn't a boolean variable.

2023-08-18 18:00 UTC, Pelentan commented on LEAF_Nexus/sources/ActiveDirectory.php
> +      return $info;
Does this need to be in our new format?  I.e. returning a json-style with results either being 1 or 2 and that data being returned in another field?  If so, please ask Jamie for the exact field names.

2023-08-18 18:00 UTC, Pelentan commented on LEAF_Nexus/sources/ActiveDirectory.php
> +      return $info;
same.

2023-08-18 18:00 UTC, Pelentan commented on LEAF_Nexus/sources/ActiveDirectory.php
> +      return $info;
ditto

2023-08-21 15:19 UTC, Pelentan approved these changes

2023-08-22 10:40 UTC, jampaul3 requested changes

2023-08-22 10:40 UTC, jampaul3 commented on LEAF_Nexus/sources/ActiveDirectory.php
> +
It's better to have an else here and only one return for this method. If you have an else here you won't need the return on line 39 you can wait and only have the one return on line 51

2023-08-22 10:40 UTC, jampaul3 commented on LEAF_Nexus/sources/ActiveDirectory.php
>        }
Same

2023-08-22 10:40 UTC, jampaul3 commented on LEAF_Nexus/sources/ActiveDirectory.php
>        }
And again

2023-08-22 15:12 UTC, aerinkayne approved these changes

2023-08-22 17:06 UTC, shaneodd approved these changes

2023-08-29 13:13 UTC, merged