Leaf 2784 - comments on cancel
department-of-veterans-affairs/LEAF pull request #2097
Opened 2023-08-23 11:08 UTC by jampaul3

There is now a textarea in the cancel dialog box for a user to enter a comment if they want. Saves it to view history.

2023-08-23 13:02 UTC, raphaelfretter approved these changes

2023-08-23 13:21 UTC, Pelentan requested changes

2023-08-23 13:21 UTC, Pelentan commented on LEAF_Request_Portal/sources/Form.php
> +    public function deleteRecord($recordID, $comment = '')
type hints and return type, please.

2023-08-23 13:31 UTC, maxrichardjr approved these changes

2023-08-23 13:46 UTC, shaneodd approved these changes

2023-08-23 17:58 UTC, mgaoVA commented on LEAF_Request_Portal/ajaxIndex.php
> +        /* This endpoint has been deprecated as of 8/31/2023 */
Please also open an issue to track future cleanup of deprecated endpoints. Example: https://github.com/department-of-veterans-affairs/LEAF/issues/2062

2023-08-24 18:38 UTC, jampaul3 commented on LEAF_Request_Portal/sources/Form.php
> +    public function deleteRecord($recordID, $comment = '')
Done

2023-08-25 11:58 UTC, aerinkayne approved these changes

2023-08-25 12:59 UTC, Pelentan approved these changes

2023-08-25 17:30 UTC, AmandaSumner approved these changes

2023-08-28 20:20 UTC, maxrichardjr approved these changes

2023-08-29 13:03 UTC, aerinkayne approved these changes

2023-08-29 13:08 UTC, merged