Test automation GFE
department-of-veterans-affairs/LEAF pull request #2116
Opened 2023-08-30 17:53 UTC by maxrichardjr

Re-PRing all Test Automation Files

2023-08-31 11:24 UTC, raphaelfretter requested changes

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/.gitignore.bak
Remove this file. Shouldn't need to be in the repo.

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/Execution/formsWorkflowPart2_BAK.java
Do we need backups for existing files on the repo here?

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/Execution/formsWorkflowPart3_BAK.java
Here too

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/Execution/formsWorkflow_BAK.java
And here.

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/PP-Demo-1_allTestsChrome.xml
> +<!--    -->
empty comment

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/PP-Demo-2_allTestsChrome.xml
> +<!--    -->
empty comment

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/PP_SelectTestsChrome.xml
> +<!--    -->
empty comment

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/Prod_AllTests-Demo-3.xml
> +<!--    -->
empty comment

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/Prod_AllTests.xml
> +<!--    -->
empty comment

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/Prod_Debugging.xml
> +<!--    -->
empty comment... you get the idea.

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/zArchive/GuessingGame.java
I doubt this is needed.

2023-08-31 11:24 UTC, raphaelfretter commented on test/Test-Automation-GFE/src/zArchive/arrays.java
Or this.

2023-09-05 17:07 UTC, shaneodd requested changes
Please see the comment on bak file, I see there are a couple other ones in there from the JAVA side of things as well. Now that we all can see and track these changes better.

2023-09-05 17:07 UTC, shaneodd commented on test/Test-Automation-GFE/.gitignore.bak
Probably do not need the bak file anymore now that it is part of the main branch.

2023-09-19 16:47 UTC, Pelentan approved these changes

2023-09-19 16:47 UTC, merged