Test Automation Local
department-of-veterans-affairs/LEAF pull request #2119
Opened 2023-09-01 20:59 UTC by maxrichardjr

This is where the local version of Test Automation is located (Test-Automation). Also, I created a new branch, Test-Automation-Local, which is the primary branch for local development

2023-09-07 16:25 UTC, raphaelfretter approved these changes

2023-09-08 14:17 UTC, shaneodd commented
Is the local test and the gfe tests going to conflict?

2023-09-13 18:34 UTC, shaneodd requested changes
I want to make sure that these two folders for local and gfe are not going to cause problems with each other since they appear to be slight variations of each other from first glance.

2023-09-15 10:58 UTC, jampaul3 approved these changes

2023-09-19 16:54 UTC, merged