LEAF 4038 timeline explorer infinite loop
department-of-veterans-affairs/LEAF pull request #2154
Opened 2023-09-22 14:49 UTC by aerinkayne

Adds some logic so that additional querying will only continue if the number of current query results is the same as the batch size.

Adds a check for the version property.

Adjusts some spacing.

2023-09-22 14:52 UTC, jampaul3 approved these changes

2023-09-22 14:59 UTC, shaneodd approved these changes

2023-09-22 15:11 UTC, maxrichardjr approved these changes

2023-09-22 15:25 UTC, mgaoVA requested changes
The original issue may need a closer look. It should not be necessary to check batch sizes or set limits when using formQuery.

Note that formQuery may appear as if it's in an infinite loop, however it's probably not actually stuck.

In order to provide accurate information, the database must scan all records that match the initial query. Since formQuery splits the query via SQL LIMIT, it's necessary to iterate through all rows. But how does the front-end know when to stop?

The signaling is handled by a custom HTTP header: [leaf-query: continue](https://github.com/department-of-veterans-affairs/LEAF/blob/master/LEAF_Request_Portal/js/formQuery.js#L254). When set, this tells the frontend there are still more rows to be scanned.

2023-09-22 16:20 UTC, mgaoVA approved these changes

2023-09-22 16:22 UTC, maxrichardjr approved these changes

2023-09-22 16:41 UTC, jampaul3 approved these changes

2023-09-22 17:09 UTC, Pelentan approved these changes

2023-09-22 17:33 UTC, AmandaSumner approved these changes

2023-10-02 12:05 UTC, raphaelfretter approved these changes

2023-10-03 12:19 UTC, merged