Leaf 4063.2 - references to national api endpoints
department-of-veterans-affairs/LEAF pull request #2208
Opened 2023-10-25 17:22 UTC by jampaul3

Notice the base branch

Summary:
This pulls together everything that took place in the previous 3 branches. The references to the national api's have all changed to include v1 before the national. The nginx was updated in the previous branch to handle the new api endpoint url (example of an endpoint would be api/v1/national/employee/search...). The v1 tells nginx to route it to the new app/api/v1 folder.

Potential Impact:
With changing the api endpoint, we could run into situations where the endpoint isn't structured properly. If they are structured properly there should be minimal impact as the endpoints should return the same data as before.

Improvements to be made:
make it so the return is in a json format that we choose. And that the calling method handles this new format properly.

Testing:
Full regression testing needs to be done here. Special attention needs to be paid to areas where there is a employee lookup.

2023-10-25 19:45 UTC, maxrichardjr approved these changes

2023-10-30 15:23 UTC, shaneodd approved these changes

2023-11-08 16:15 UTC, jrodcode approved these changes

2023-11-09 19:59 UTC, mgaoVA requested changes

2023-11-09 19:59 UTC, mgaoVA commented on LEAF_Nexus/admin/templates/orgChart_import.tpl
> +                    url: '../api/v1/national/employee/search?q=' + email + '&noLimit=0',
@Pelentan the current API should not be organized in a v1 like this. It creates unnecessary complexity and has downstream impact.

API related organization should be centered on v2 effort, and would require additional planning.

2024-02-07 14:39 UTC, closed without merging