LEAF_3975_FY23_WASA_Findings - 404 Issue
department-of-veterans-affairs/LEAF pull request #2211
Opened 2023-10-26 13:28 UTC by jrodcode

## Summary:
When a user enters an incorrect URL in the browser, the server will now present a customized 404 page. This is in response to a finding from the WASA report, which pointed out that the server previously displayed server-related information instead of a user-friendly error message to indicate that the requested page or file does not exist. The changes to NGINX file are on a different repository at https://github.com/department-of-veterans-affairs/LEAF-infrastructure. These enhancements involve NGINX settings to manage the handling and display of 404 pages.

## Testing:
To test this locally, follow these steps:

1. Change the value of var homepageURL from "/" to "/LEAF_Request_Portal/".

2. Update the default.conf file settings by applying the changes found in the LEAF infrastructure Pull Request (PR).

3. To trigger the 404 page, use the following example URL:
    `https://localhost/LEAF_Request_Portal/apple`
Typing the example URL will display the customized 404 page.

2023-10-26 13:30 UTC, maxrichardjr approved these changes

2023-10-26 14:19 UTC, maxrichardjr approved these changes

2023-10-26 17:57 UTC, jampaul3 approved these changes

2023-10-26 17:59 UTC, mgaoVA requested changes
See comments in PR#122 in the Infrastructure repo.

2023-11-08 21:52 UTC, mgaoVA requested changes
I think it would be better to move this file into the infrastructure repo.

A 404 page is meant to work across the entire domain. Currently it looks like it's structured within the Request Portal -- what if the 404 is being generated from Nexus or anywhere else?

Might need additional coordination with @Pelentan

2023-11-09 16:06 UTC, maxrichardjr approved these changes

2023-11-29 16:27 UTC, closed without merging