LEAF_3975_FY23_Part2
department-of-veterans-affairs/LEAF pull request #2221
Opened 2023-11-05 05:34 UTC by jrodcode

## Summary
The second part of this PR has to do with cleaning code.

2023-11-06 13:39 UTC, jampaul3 approved these changes

2023-11-06 13:51 UTC, maxrichardjr approved these changes

2023-11-06 15:28 UTC, mgaoVA requested changes

2023-11-06 15:33 UTC, mgaoVA requested changes

2023-11-06 15:33 UTC, mgaoVA commented on LEAF_Nexus/auth_cookie/index.php
>          $redirect = $protocol . HTTP_HOST . dirname($_SERVER['PHP_SELF']) . '/../';
This should be used to initialize $redirect as the default. This would avoid having a blank redirect due to the new nested conditions.

2023-11-09 14:37 UTC, maxrichardjr approved these changes

2023-11-09 19:47 UTC, mgaoVA requested changes

2023-11-09 19:56 UTC, jrodcode commented on LEAF_Nexus/auth_token/index.php
> +        $parsedRedirect = parse_url($decodedRedirect);
Sounds good, I make the changes. Thank you.

2023-11-15 14:14 UTC, shaneodd approved these changes

2023-11-16 23:59 UTC, maxrichardjr approved these changes

2024-05-16 12:50 UTC, closed without merging