LEAF 4223 idea inbox customizations
department-of-veterans-affairs/LEAF pull request #2287
Opened 2024-02-12 19:35 UTC by aerinkayne

**Combined Inbox Editor (beta) and LEAF_Inbox options updates**

-Fix bug that causes non portal sitemap cards to be deleted.

-Fix error that occurred if the sitemap card target does not end in a slash.

-Add js XSSHelpers to strip out all potential HTML in custom header names and update custom headers to use the short label if it's available instead of the full indicator name for the multiselect plugin options.

-Add Priority and Date Submitted header options.  Inbox view will automatically sort by priority if this header is present.

-Add ability to add form-specific settings for indicator questions.

-Inbox View 508 Adjustments:
Category Headers are now buttons instead of divs for keyboard accessibility.
Top buttons for view and organization options now tab left to right.

**Testing / Impact**
This update is specific to the admin side Combined Inbox Editor and the combined inbox view (LEAF_Inbox).
Errors noted above should no longer occur on the Inbox Editor, and both the Editor and Inbox should otherwise continue to behave as expected.

2024-02-13 14:37 UTC, shaneodd approved these changes

2024-02-13 19:00 UTC, jampaul3 approved these changes

2024-02-21 20:03 UTC, Pelentan requested changes

2024-02-21 20:03 UTC, Pelentan commented on LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
> +            let cols = formColumns[key];
Variables shouldn't be defined inside of loops.  The definition  should be set outside, and then use a conditional assignment so it either puts in the new value or null.

2024-02-21 20:03 UTC, Pelentan commented on LEAF_Request_Portal/templates/reports/LEAF_Inbox.tpl
> +            const col = allColumns[i];
Same here.

2024-02-22 15:34 UTC, Pelentan approved these changes

2024-02-27 17:25 UTC, merged