Simplify ./api/form/specified structure
department-of-veterans-affairs/LEAF pull request #2385
Opened 2024-05-02 22:17 UTC by mgaoVA

Instead of wrapping content into an arbitrary structure, HTTP status codes should be used instead.

Note that the fetch() related to this already implements a catch(), capturing unsuccessful responses.

### Potential Impact
- This changes the response structure of `api/form/specified`, but it's apparently only used in one place.

### Testing
- [ ] `api/form/specified` isn't used anywhere else
- [ ] Form Preview works normally when the form contains a stapled form

2024-05-03 12:35 UTC, aerinkayne approved these changes

2024-05-03 14:07 UTC, Pelentan approved these changes

2024-05-03 14:07 UTC, mgaoVA commented
Note added prerequisite

2024-05-03 14:24 UTC, jampaul3 approved these changes

2024-05-03 15:39 UTC, shaneodd approved these changes

2024-05-06 11:55 UTC, aerinkayne requested changes
Updating this, since the key change is here too.
We will need to address the sorting issue along with the numeric keys change.

2024-05-06 14:08 UTC, aerinkayne approved these changes
Approving with comment to make sure this goes along with 4336, which now has the sorting update

2024-05-14 14:00 UTC, closed without merging