formSearch.js cleanup
department-of-veterans-affairs/LEAF pull request #2395
Opened 2024-05-07 01:11 UTC by mgaoVA

This resolves a few edge-cases related to the formSearch widget.

Additionally, this hides references to built-in forms behind the "dev" GET parameter to reduce clutter.

Steps to reproduce Issue 1:
1. Open the Data Visualizer
2. Select a form
3. Click on `Edit Filter`
4. Click on `Apply Filters`
5. Click on `Edit Filter` 
6. Note that excess search options are incorrectly included

Steps to reproduce Issue 2:
1. On the homepage in the search area, click on `Advanced Options`
2. Change the search term to `Record ID`
3. Change the search term back to `Current Status`
4. Note that the dropdown of status options is missing

Steps to reproduce Issue 3:
1. Open the Report Builder
2. Note that every time you click on `And...`, an network transaction is incorrectly made

Steps to reproduce Issue 4:
1. Open the Homepage (with a cleared search bar)
2. Note that there is an unnecessary network request to `api/workflow/steps`

### Potential Impact
- Everywhere formSearch.js is used, such as the Homepage and Report Builder Step 1

### Testing
- [ ] The issues outlined above cannot be reproduced
- [ ] Homepage search options are recalled correctly through page refreshes
- [ ] Report Builder -> Modify Search -> Search options are recalled correctly
- [ ] On the Homepage search when "Current Status" is selected, there is no reference to "Leaf Developer Console".

2024-05-08 17:53 UTC, Pelentan requested changes

2024-05-08 17:53 UTC, Pelentan commented on LEAF_Request_Portal/js/formSearch.js
> +                for (var i in allStepsData) {
This needs to be a "let"

2024-05-08 17:53 UTC, Pelentan commented on LEAF_Request_Portal/js/formSearch.js
> +                        if(new URLSearchParams(window.location.search).get('dev') == null) {
I'm thinking this needs a fail/catch.  If it gets something weird back from the network it could have odd consequences down the line.

2024-05-08 19:16 UTC, mgaoVA commented on LEAF_Request_Portal/js/formSearch.js
> +                for (var i in allStepsData) {
Updated

2024-05-08 19:22 UTC, aerinkayne approved these changes

2024-05-09 13:33 UTC, Pelentan approved these changes

2024-05-09 13:43 UTC, shaneodd approved these changes

2024-05-09 18:39 UTC, jampaul3 approved these changes

2024-05-14 14:01 UTC, merged