Query step actions
department-of-veterans-affairs/LEAF pull request #2398
Opened 2024-05-09 00:10 UTC by mgaoVA

This expands `api/form/query`: Find all records if a specific action was taken for a given step.

No additional DB indexes seem to make a meaningful difference in query performance. Observed up to 0.14s query time on a site containing 2M actions.

Automated tests pending conflict resolution with PR#2390

### This PR is dependent on:
- https://github.com/department-of-veterans-affairs/LEAF/pull/2395
- https://github.com/department-of-veterans-affairs/LEAF/pull/2390

### Potential Impact
Minimal because this adds new functionality without touching existing logic.

### Testing
- [ ] Passes automated tests
- [ ] Create a record and apply actions to it. Using the Homepage Advanced Search or Report Builder, use the new `Record Actions ...` term to find the record by using matching Step and Actions.

2024-05-09 18:30 UTC, jampaul3 approved these changes

2024-05-10 14:02 UTC, shaneodd approved these changes

2024-05-16 13:10 UTC, Pelentan requested changes

2024-05-16 13:26 UTC, mgaoVA commented on LEAF_Request_Portal/js/formSearch.js
> +        url =
Yeah this is pretty ugly. I hope I'm not the one who originally wrote it :P

2024-05-16 13:31 UTC, mgaoVA commented on LEAF_Request_Portal/js/formSearch.js
> +                        cache['api/workflow/steps'] = $.ajax({
Updated

2024-05-16 14:00 UTC, mgaoVA commented on LEAF_Request_Portal/sources/Form.php
> +                            // loops within a workflow, and people can take different actions later
I thought that too when I saw this technique, but it's actually pretty fast: `Observed up to 0.14s query time on a site containing 2M actions.`, especially considering it's a tough query and we don't need to touch the schema.

In this case it's faster to keep all the processing in the DB. Using the above test, it lets PHP avoid having to process about 75% of the records, and avoid overhead from additional queries.

2024-05-22 13:32 UTC, jampaul3 approved these changes

2024-05-23 14:23 UTC, Pelentan approved these changes

2024-05-28 23:50 UTC, mgaoVA commented
@Pelentan I rebased this onto Sprint-75-c1 + https://github.com/department-of-veterans-affairs/LEAF/pull/2419, and added an automated test.

2024-05-29 17:43 UTC, merged