Optimize formGrid.js rendering
department-of-veterans-affairs/LEAF pull request #2424
Opened 2024-06-01 20:47 UTC by mgaoVA

This improves rendering/sort performance by about 60% on my machine when using the test page below.

The two key optimizations implemented are:
- Replace jQuery with vanilla JS in hotspots
- Moved [this querySelector so that it runs before](https://github.com/department-of-veterans-affairs/LEAF/compare/rc/2024-05-29/Sprint-75-c2...formGrid-ux?expand=1#diff-44a38b730a68b0a6678696a5a7b27c75fee777b14ae493226ebbc623db0c2c48R368) adding potentially millions of DOM elements.

This also includes minor updates the Report Builder:
- Use formQuery.js's batching feature instead of its own
- Use formQuery.js's setAbortSignal() method to improve the reliability of the "Stop" button
- Resolve issue with "Create Row" button showing up when it shouldn't

Before:
![Screenshot 2024-06-01 101546](https://github.com/department-of-veterans-affairs/LEAF/assets/16783916/f6352d9f-8ef4-4ea9-b8c8-e25f0c362342)

After:
![Screenshot 2024-06-01 155643](https://github.com/department-of-veterans-affairs/LEAF/assets/16783916/2a95065b-66e5-4d2e-82ce-5375af4ecf42)

Test page simulating a large report:
- To reproduce the test: Load this page, and click one of the headers to sort.
```html
<style>
#content {
    margin: 1rem;
}
</style>
<script>
async function main() {
    // Generate random data
    let numCols = 8;
    let data = {};
    for(let i = 0; i < 10000; i++) {
        data[i] = {};
        for(let j = 0; j < numCols; j++) {
            data[i][j] = Math.random() * 100000;
        }
    }

    let formGrid = new LeafFormGrid('grid');
    formGrid.enableToolbar();
    formGrid.setData(Object.keys(data).map(key => {
        data[key].recordID = key;
        return data[key];
    }));
    formGrid.setDataBlob(data);

    let headers = [];
    for(let j = 0; j < numCols; j++) {
        headers.push({name: `Col${j}`, indicatorID: `Col${j}`, editable: false, callback: function(data, blob) {
            // Simulate old report builder using jQuery
            $('#'+data.cellContainerID).html(blob[data.recordID][j]);

            // Simulate new report builder without jQuery
            //document.querySelector(`#${data.cellContainerID}`).innerHTML = blob[data.recordID][j];
        }});
    }
    formGrid.setHeaders(headers);
    formGrid.renderBody();
}

document.addEventListener('DOMContentLoaded', main);
</script>

<h1>Grid Performance Test</h1>
<div id="grid"></div>
```

### Potential Impact
Dependencies of formGrid.js, especially the Report Builder, Homepage, and Inbox.

### Testing
- [ ] Sorting in the Report Builder works normally

2024-06-03 14:08 UTC, Pelentan approved these changes

2024-06-03 19:05 UTC, shaneodd approved these changes

2024-06-03 20:23 UTC, aerinkayne approved these changes

2024-06-03 20:43 UTC, mgaoVA commented
@Pelentan fixed issue with missing style found by @aerinkayne

2024-06-04 21:40 UTC, mgaoVA commented
Flagging as draft, issue with needing to re-apply events after rendering from cache

2024-06-05 01:20 UTC, mgaoVA commented
@aerinkayne The issue with events should be fixed now. Used a different caching approach, and I also updated the test page to include event listeners

2024-06-07 17:14 UTC, Pelentan requested changes
There seems to be a lot going on with optimization.  Do we want some Go tests for them?

2024-06-10 13:06 UTC, aerinkayne approved these changes

2024-06-10 14:02 UTC, shaneodd approved these changes

2024-06-10 14:10 UTC, jampaul3 approved these changes

2024-06-17 13:47 UTC, Pelentan approved these changes

2024-06-21 13:32 UTC, mgaoVA commented
Already merged

2024-06-21 13:32 UTC, closed without merging