File manager: last modified date
department-of-veterans-affairs/LEAF pull request #2441
Opened 2024-06-13 14:14 UTC by mgaoVA

This adds a "Last Modified" column to the File Manager.

API Change:
- `./api/system/files` now accepts the optional GET parameter `getLastModified`. When set, it includes the last modified time for each file.

## Potential Impact
- Impact due to API change mitigated via use of backward compatible $_GET flag
- CSS style for leaf_grid was updated in the admin area. This might actually indirectly fix styling for the LEAF Library, which can only be checked in pre-prod.

## Testing
- [ ] Files and their last modified dates show up correctly in the File Manager

2024-06-13 14:23 UTC, jampaul3 approved these changes

2024-06-13 14:25 UTC, shaneodd approved these changes

2024-06-17 13:42 UTC, Pelentan requested changes

2024-06-17 13:42 UTC, Pelentan commented on LEAF_Request_Portal/sources/System.php
> +    public function getFileList($getLastModified = false)
Please update with typehinting and return type.

2024-06-26 13:13 UTC, merged