LEAF 4402 update gridsplitter to use formQuery
department-of-veterans-affairs/LEAF pull request #2449
Opened 2024-06-14 19:06 UTC by aerinkayne

Updates the grid-splitter report to use formQuery methods to query the selection rather than getting data for each record.
Minor style updates.

**Testing / Impact**

LEAF Programmer built-in report: LEAF_table_input_report

Confirm that grid format question entries for submitted requests can be split into columns and downloaded

2024-06-17 13:55 UTC, Pelentan requested changes

2024-06-17 13:55 UTC, Pelentan commented on LEAF_Request_Portal/templates/reports/LEAF_table_input_report.tpl
> +function addRecordData(recordID, indicatorID, gridInput = {}) {
Do we want some defaults here?  Additionally, is indicatorID even being used?  If it's here for legacy sake, we may want to indicate that.

2024-06-18 13:26 UTC, jampaul3 approved these changes

2024-06-18 15:32 UTC, shaneodd approved these changes

2024-06-21 14:27 UTC, Pelentan approved these changes

2024-06-26 15:16 UTC, merged