LEAF-4426: VAPO Automated Emails
department-of-veterans-affairs/LEAF pull request #2474
Opened 2024-07-15 12:30 UTC by pete-nerantzinis

2024-07-15 13:16 UTC, Pelentan requested changes

2024-07-15 13:16 UTC, Pelentan commented on scripts/scheduled-task-commands/automatedEmailReminderVAPO.php
> +    echo "Portal: " . $dir . $site['site_path'] . '/scripts/automated_email.php' . "\r\n";
I'm thinking we should make the output (echos) actually go to a log file.  Make it easier to troubleshoot and we can get Dynatrace to watch it that way.

2024-07-15 14:15 UTC, jampaul3 approved these changes

2024-07-15 15:51 UTC, mgaoVA commented
> _ No description provided. _

Please update to summarize what this is about, and also highlight potential issues/prerequisite tasks.

2024-07-16 15:13 UTC, shaneodd approved these changes

2024-07-17 17:49 UTC, Pelentan approved these changes

2024-07-17 17:50 UTC, merged