Leaf 4465 - Nexus 508 updates
department-of-veterans-affairs/LEAF pull request #2528
Opened 2024-08-21 18:43 UTC by jampaul3

Nexus Orgchart navigator and editor

Page needs a number of improvements

Additional info to user on overview page about what the page is conveying and what can be edited (brief ok)

Drag behavior in the editor should be available from keyboard

Tab order at least appears unintuitive.  There is a number associated with each cell that might mediate this.  Tabbing should be tree breadth so presentation alone might resolve this

Doublecheck how / when associated dropdowns collapse - tabbing away and full mouse off should close them

Potential Impact:
These changes should make it easier for people to navigate the orgchart navigator and editor with the keyboard.

Testing:
Open the orgchart and click browse.
using only the keyboard tab through the page. Once you get to the different positions they should tab in hierarchy order, Level 1 to level 2 to level 3 and so on.
If you press enter on the edit orgchart from the navigator page you enter the editor page. 
tabbing through the page again should tab through the hierarchy order. 
There is a new button name move coordinates for each of the positions.
Pressing enter on move coordinates will allow you to use the arrow keys to move the position around the screen.
Pressing Esc will return the position to it's original coordinates and exit the eventListener.
Pressing Enter will save the newcoordinates and exit the eventListener.

2024-08-26 13:02 UTC, Pelentan requested changes
Whole lotta changes in here that I'm not sure are needed.  As well as "vars".

2024-08-26 13:02 UTC, Pelentan commented on LEAF_Nexus/js/ui/position.js
> +  var pd = response[9].data != '' ? 'PD#' + response[9].data : ''
I'm seeing a whole lot of var's all through this.  Are they required?

2024-08-26 13:02 UTC, Pelentan commented on LEAF_Nexus/js/ui/position.js
> +    var y = 120
I know they aren't needed here.

2024-08-27 19:38 UTC, jampaul3 commented
redoing this to keep formatting where it was.

2024-08-27 19:38 UTC, closed without merging