LEAF 4526 prevent copying of request if form is hidden
department-of-veterans-affairs/LEAF pull request #2553
Opened 2024-09-18 18:55 UTC by aerinkayne

This issue is associated with a help desk ticket where users were able to create hidden forms.  
Forms had been created through Tools -> Copy Request convenience feature.  

This update will prevent the copy of requests associated with forms that are in a hidden state.  Alternate information will be presented to the user instead of the copy inputs.  It also includes some updates to the input modal to improve responsiveness and address label issues.

**Testing / Impact**
Form Copy Feature on the printview (Tools -> Copy Request).

Confirm that form copy feature continues to work as expected for non-hidden forms.
Confirm all form elements in the normal modal are associated with labels.
Confirm that the alternate message displays if forms associated with the request are in a hidden state (toggle visibility to hidden in the form editor).

2024-09-19 14:39 UTC, Pelentan approved these changes

2024-09-19 19:59 UTC, shaneodd approved these changes

2024-09-20 00:23 UTC, mgaoVA requested changes
A different approach needs to be taken.

The core issue is:
> users were able to create [requests based on] hidden forms

We should prevent requests from being created if the form is marked as hidden.

Therefore:
1. Form.php -> newForm() should be updated to return an error string if the form is marked as hidden.
2. The "Copy Request" feature should show the error message.

2024-09-24 19:14 UTC, jampaul3 approved these changes

2024-09-26 13:28 UTC, jampaul3 approved these changes

2024-09-26 14:55 UTC, Pelentan approved these changes

2024-09-26 20:25 UTC, shaneodd approved these changes

2024-10-01 16:35 UTC, merged