LEAF-4604 update form progress checking to account for conditional logic
department-of-veterans-affairs/LEAF pull request #2613
Opened 2024-12-03 13:42 UTC by aerinkayne

The current Form getProgress method still compares a flat array of required questions with data entries in order to determine form progress percentage.  Individual questions account for direct conditional logic.  However, since there is no information about form structure, using conditional logic when the conditional indicator has required sub-questions is problematic / tedious because the logic needs to be repeated on the subquestion.

This update will take form structure into account (when needed) during the progress count so that any ancestor in a hidden state is sufficient.

**Front end:**
Updates to form.js to handle conditional display states and to toggle front end validation for required questions

**Server-Side:**
Updates to form method getProgress to account for structure.
Following a check for submission and for the number of required questions, method will progress with a depth search assessment of question display state, visible required question, and total required question totals.  Required questions that are not in a visible state because they OR one of their ancestors are hidden by conditional do not count towards the visible total.

**Impact / Testing.**

This has high impact to the initial request submission process.
If the total is inaccurate
-data entry or submission could be prevented without a visible indication to the user as to why.
-submission could be allowed despite the user not having answered all required questions.

Test form data entry (initial request) and confirm that the percentage (form progress) reflects the percentage of answered required questions that are visible on the form.  Required questions hidden by ifthen logic directly, or because they are subquestions of hidden questions should not count towards the visisble total.

2024-12-03 21:32 UTC, shaneodd approved these changes

2024-12-04 14:28 UTC, jampaul3 approved these changes

2024-12-04 15:13 UTC, Pelentan requested changes

2024-12-04 15:13 UTC, Pelentan commented on LEAF_Request_Portal/sources/Form.php
> +    private function count_required(
Where's my return type?  ;-)

2024-12-04 15:13 UTC, Pelentan commented on LEAF_Request_Portal/sources/Form.php
> +    public function getProgress($recordID)
Type cast and return type, please.

2024-12-09 15:45 UTC, Pelentan submitted a review, later dismissed

2024-12-10 14:15 UTC, shaneodd approved these changes

2024-12-10 14:26 UTC, jampaul3 approved these changes

2024-12-12 16:07 UTC, merged