Leaf 4376 - update user name part 2
department-of-veterans-affairs/LEAF pull request #2616
Opened 2024-12-10 19:25 UTC by jampaul3

Summary:
A way is needed to prevent a userName from being recycled and the new person being able to view data that does not belong to them.

Potential Impact:

Testing:
The only way to test this is on staging. And that is to run the script. Ensure that only those users who are disabled actually get their userName updated.

2024-12-13 19:23 UTC, shaneodd requested changes
Looks like some input/return types are missing? Looks like some areas have it.

2024-12-13 19:23 UTC, shaneodd commented on app/Leaf/VAMCActiveDirectory.php
> +    public function importADData($file)
Return types?

2024-12-13 19:23 UTC, shaneodd commented on app/Leaf/VAMCActiveDirectory.php
> +    private function getNewlyDeletedUsers($time): array
Input type?

2024-12-17 20:10 UTC, shaneodd approved these changes

2024-12-17 20:38 UTC, aerinkayne approved these changes

2024-12-18 13:17 UTC, Pelentan approved these changes

2024-12-19 12:59 UTC, merged